### ISSUE TITLE
Empty vehicles are respawning every 3 minutes

### ISSUE THREAD

**Issue by tanaaKa** [TheTexasHawk49/Desert-Scorpion#7]
Regardless of situation, 3 minute respawns on all empty vehicles

**Comment by tanaaKa** [comment]
@Jester2138

**Comment by JesseHaycraft** [comment]
Checking

**Comment by JesseHaycraft** [comment]
@tanaaKa @TheTexasHawk49 created pull request for new vehRespawn which hopefully will fix it.

**Comment by tanaaKa** [comment]
The 200m check doesnt appear to be working so far. I stood out by a vehicle for 30mins afk and it respawned.

**Comment by tanaaKa** [comment]
And just checked the respawn timer. Still 3 minutes.

**Comment by JesseHaycraft** [comment]
tbh I've been awake for 22 hours at this point so I'm a bit unreliable. Can you check this getVarible "sideLocInfo" and "CCE_idleChecker" on a respawn vehicle serverside and see what it does @tanaaKa @TheTexasHawk49

**Comment by JesseHaycraft** [comment]
btw the idle period should be about 2.5 minutes not 3

**Comment by JesseHaycraft** [comment]
Still not fixed

**Comment by JesseHaycraft** [comment]
Should be fixed in https://github.com/TheTexasHawk49/Desert-Scorpion/commit/0745da0d6232cdf5eea473d6e6e66d3b34438a2b

Set up so if a vehicle is abandoned > 200m for 3 minutes, it'll delete and start respawn timer. User-configurable at top of script.

NOTE: vehicles that are used for a side other than their mod config'd side need additional handling. I will explain later because I might change my mind on how this issue is handled by the user. @TheTexasHawk49

**Comment by JesseHaycraft** [comment]
I updated the artillery assets to be available to all sides natively, so no special configuration is needed for this script.
